import type { ResearchGoal, AgentReply, AgentPlan, ResearchCandidate, RebalanceDraft } from './research-agent-types';
import type { ResearchStrategy } from './research-workspace';
import type { PreparedTrade } from './stock-trade-review';
import { ResearchStore } from './research-store.mjs';
import type {DatabaseSync} from 'node:sqlite';
import type {AgentProfile} from './research-agent-profile.mjs';
export const AGENT_VERSION:string;
export function hash(x:unknown):string;
export function canonical(x:unknown):string;
export function reject(message:string,status?:number):never;
export function validateGoal(value:unknown):ResearchGoal;
export function briefHash(value:unknown):string;
export function budgetAtoms(value:string,decimals?:number):string;
export class AgentStore extends ResearchStore {
  db:DatabaseSync;
  owner(address:string):string;
  get(owner:string,id:string):ResearchStrategy;
  transaction<T>(fn:()=>T):T;
  reserveTokens(maximum:number,cap?:number):{day:string;maximum:number}|null;
  tokenResult(ticket:{day:string;maximum:number},actual?:number|null):void;
  enqueue(address:string,strategyId:string,goal:unknown,requestId:string):string;
  view(address:string,strategyId:string,after?:number):AgentReply;
  cancel(address:string,id:string):void;
  reviewCandidate(address:string,runId:string,candidateId:string,reportHash:string):{strategy:ResearchStrategy;candidate:ResearchCandidate;input:unknown};
  saveRebalanceDraft(address:string,runId:string,candidateId:string,reportHash:string,allocation:unknown):RebalanceDraft;
  approve(address:string,runId:string,candidateId:string,reportHash:string,draftId?:string|null):AgentPlan;
  approveReplacingUnused(address:string,runId:string,candidateId:string,reportHash:string,draftId:string|null,discardDraft:(owner:string,id:string)=>Promise<unknown>):Promise<AgentPlan>;
  plan(address:string,id:string):AgentPlan;
  claimAutonomy(address:string,id:string,policyId:string):void;
  syncAutonomy(address:string,id:string,execution:unknown):void;
  reserveStep(address:string,id:string,index:number):{plan:AgentPlan;existing:PreparedTrade|null};
  bindPrepared(address:string,id:string,index:number,prepared:unknown,quote:unknown):void;
  releaseUnsignedPreparation(address:string,id:string,index:number):void;
  step(address:string,id:string,index:number):{plan:AgentPlan;phase:string;prepared:PreparedTrade};
  authorizeSubmit(address:string,id:string,index:number):{plan:AgentPlan;phase:string;prepared:PreparedTrade};
  recordStep(address:string,id:string,index:number,phase:string,observation?:unknown):void;
  revoke(address:string,id:string):void;
  monitor(address:string,strategyId:string,goal:unknown,enabled:boolean):unknown;
  agents(address:string):AgentProfile[];
  agentProfile(owner:string,id:string):AgentProfile;
  saveAgent(address:string,body:unknown):AgentProfile;
  assertAgentCurrent(owner:string,agent:{id:string;revision:number}|null|undefined):AgentProfile|null;
  assertAutonomyAllowed(address:string,plan:AgentPlan):void;
  bscStep(address:string,id:string,index:number):{plan:AgentPlan;phase:string;doc:BscStepDoc};
  assertBscPreparable(address:string,id:string,index:number,nonceNow:string):{plan:AgentPlan;doc:BscStepDoc};
  bscPrepared(address:string,id:string,index:number,kind:'APPROVE'|'SWAP',prepared:{tx:Record<string,string>;quote?:unknown;simulation?:unknown},nonce:string):BscPrepared;
  bscSent(address:string,id:string,index:number,hash:string):BscStepDoc;
  bscReceipt(address:string,id:string,index:number,receipt:{status:string;blockNumber?:number}|null):BscStepDoc;
}
export type BscPrepared={kind:'APPROVE'|'SWAP';tx:Record<string,string>;quote:unknown;simulation:unknown;nonce:string;at:number};
export type BscStepDoc={leg:unknown;prepared?:BscPrepared;sent?:{hash:string;kind:string;at:number};receipts?:unknown[]};
export function chainOf(address:string):'bsc'|'solana';
export function budgetUnit(address:string):{asset:'USDT'|'USDC';decimals:number};
export const BSC_MIN_LEG_ATOMS:bigint;
