#!/usr/bin/env python3
"""Regenerate web/lib/bsc-research-themes.mjs: discovery groups for BNB Chain research, built from data instead of a
hand-written list. Run on the host that has the research data (prices + fundamentals releases):

  python dev/gen_bsc_themes.py <data root> <bsc universe json: {"tickers": [...], "funds": [...]}> <out.mjs>

Groups are filters on objective facts (SIC sector, dividends paid, trailing dollar volume, whether filings exist),
ranked by liquidity. They only seed a research draft that the user reviews; the agent's rules and the backtests decide.
"""
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "engine/agent"), str(ROOT / "engine/compute")]
import numpy as np                                        # noqa: E402
from xtxc_agent.research import fundamentals as F, volume as V   # noqa: E402
from evaluate import load_prices                          # noqa: E402

PER_THEME = 20
SECTOR_THEMES = {"technology": ["technology"], "healthcare": ["health_care"], "finance": ["financials"],
                 "consumer": ["consumer_discretionary", "consumer_staples"], "energy": ["energy"], "industrials": ["industrials"],
                 "utilities": ["utilities"], "materials": ["materials"], "real_estate": ["real_estate"], "communication": ["communication"],
                 "crypto": ["digital_assets"]}
SEMI_SIC = {"3674", "3559"}   # semiconductors and related devices; special industry machinery (chip equipment)
AI = ["NVDA", "AMD", "AVGO", "TSM", "MU", "MRVL", "GOOGL", "META", "AMZN", "ORCL", "PLTR", "MSFT", "SMCI", "ANET", "DELL", "VRT"]
BROAD = ["SPY", "QQQ", "VTI", "IVV", "IWM"]

root, universe, out = Path(sys.argv[1]), json.loads(Path(sys.argv[2]).read_text()), Path(sys.argv[3])
tickers, funds = universe["tickers"], set(universe["funds"])
docs, meta = F.load_release(root)
rel = json.loads((root / "fundamentals" / "release.json").read_text())["tickers"]
closes, _ = load_prices(root, tickers, column="close", common=False)
volumes, _ = load_prices(root, tickers, column="volume", common=False)
facts = {}
for t in tickers:
    c, v = closes[t].dropna(), volumes[t].dropna()
    dv = V.ticker_panel(c, v.reindex(c.index))["dollar_volume"]
    row = {"dollars": float(10 ** dv[-1]) if len(dv) and math.isfinite(dv[-1]) else 0.0, "fund": t in funds,
           "sector": meta["sectors"].get(t), "sic": (rel.get(t) or {}).get("sic")}
    if t in docs and not row["fund"]:
        p = F.attach(c.to_frame()[[]], c.to_frame(), {t: docs[t]}, {t}, None, meta["fx"], F.split_events(root, [t]))
        p = {k.split("::")[1]: p[k].to_numpy() for k in p.columns}
        row["filings"] = bool(np.isfinite(p["earnings_yield"][-1]) and np.isfinite(p["book_to_price"][-1]))
        row["dividend"] = float(p["dividend_yield"][-1]) if np.isfinite(p["dividend_yield"][-1]) else None
    facts[t] = row


def top(names):
    return sorted(dict.fromkeys(names), key=lambda t: (-facts[t]["dollars"], t))[:PER_THEME]


def spread(names):
    """Most traded first, taking turns across sectors so one sector cannot fill the list."""
    groups: dict = {}
    for t in sorted(dict.fromkeys(names), key=lambda t: (-facts[t]["dollars"], t)):
        groups.setdefault(facts[t]["sector"], []).append(t)
    out = []
    while len(out) < PER_THEME and any(groups.values()):
        for g in list(groups.values()):
            if g and len(out) < PER_THEME:
                out.append(g.pop(0))
    return out


companies = [t for t in tickers if not facts[t]["fund"]]
with_filings = [t for t in companies if facts[t].get("filings") and facts[t]["sector"] not in (None, "digital_assets")]
themes = {"ai": [t for t in AI if t in facts],
          "semiconductors": top(t for t in companies if facts[t]["sic"] in SEMI_SIC),
          **{k: top(t for t in companies if facts[t]["sector"] in s) for k, s in SECTOR_THEMES.items()},
          "dividend": top(t for t in with_filings if (facts[t].get("dividend") or 0) >= 0.02),
          "value": spread(with_filings),
          "broad_market": [t for t in BROAD if t in facts]}
themes = {k: v for k, v in themes.items() if v}
starter = spread(with_filings)
out.write_text(
    "// Discovery groups for BNB Chain research, generated by dev/gen_bsc_themes.py from the research data\n"
    f"// (price release {json.loads((root / 'prices' / 'quant_release.json').read_text())['release_id'][:12]}, "
    f"fundamentals release {meta['releaseId'][:12]}). Each group is a filter on facts (SIC sector, dividends paid,\n"
    f"// filings on record), ranked by 20-day dollar volume, at most {PER_THEME} names. They seed a draft the user reviews;\n"
    "// they are not recommendations. The agent's rules and the backtests decide.\n"
    f"export const BSC_THEMES=Object.freeze({json.dumps(themes, indent=1)});\n"
    "// Used when a request names no stock or theme: the most traded companies with filings on record, taking turns\n"
    "// across sectors, so both technical and value agents have something to work with.\n"
    f"export const BSC_STARTER=Object.freeze({json.dumps(starter)});\n")
print(json.dumps({k: len(v) for k, v in themes.items()} | {"starter": len(starter)}))
