#!/usr/bin/env python3
"""Regenerate web/lib/bsc-research-universe.mjs: research tickers with enough verified price history that trade on
BNB Smart Chain as Ondo or bStock tokens.

  python3 dev/gen_bsc_universe.py <gateway /v1/universe JSON> <quant_release.json> [out]

Only tokens that are not UNSUPPORTED are kept; a ticker needs MIN_ROWS sessions (a one-year research horizon needs
3 x 252 + 379 common sessions). Execution re-checks the live status and the contract before every trade."""
import json
import re
import sys
from pathlib import Path

MIN_ROWS = 1135
FUND = re.compile(r"\b(ETF|Fund|Trust|iShares|SPDR|Invesco|ProShares|Direxion|VanEck|Treasury|Bond|Index)\b", re.I)

live = json.loads(Path(sys.argv[1]).read_text())["data"]
release = json.loads(Path(sys.argv[2]).read_text())["tickers"]
out = Path(sys.argv[3] if len(sys.argv) > 3 else "web/lib/bsc-research-universe.mjs")
products, names, funds = {}, {}, set()
for t in live["tokens"]:
    u = t.get("underlying")
    if not u or t["status"]["reason"] == "UNSUPPORTED" or release.get(u, {}).get("rows", 0) < MIN_ROWS:
        continue
    products.setdefault(u, {})[t["platform"]] = {"contract": t["contract"].lower(), "decimals": int(t["decimals"]),
                                                 "ratio": t["ratio"], "symbol": t["symbol"]}
    names.setdefault(u, re.sub(r"\s*\((Ondo Tokenized|Ondo|bStocks?)\)\s*$", "", t["name"]))
    if FUND.search(t["name"]):
        funds.add(u)
products = dict(sorted(products.items()))
out.write_text(
    "// Research tickers with verified price history that trade on BNB Smart Chain as Ondo or bStock tokens.\n"
    f"// Generated by dev/gen_bsc_universe.py from Binance Web3 RWA Data (rwa/tokens, chain 56) observed {live['observedAt']};\n"
    f"// UNSUPPORTED tokens and tickers with under {MIN_ROWS} sessions of history are excluded.\n"
    "// Execution re-checks the live status and refuses if a live contract differs from this snapshot.\n"
    f"export const BSC_SNAPSHOT_AT={json.dumps(live['observedAt'])};\n"
    f"export const BSC_RESEARCH_PRODUCTS={json.dumps(products, indent=1, sort_keys=True)};\n"
    f"export const BSC_RESEARCH_NAMES=Object.freeze({json.dumps(dict(sorted((k, names[k]) for k in products)), indent=1, ensure_ascii=False)});\n"
    f"export const BSC_RESEARCH_FUNDS=Object.freeze({json.dumps(sorted(funds))});\n"
    "export const BSC_RESEARCH_STOCKS=Object.freeze(Object.keys(BSC_RESEARCH_PRODUCTS).sort());\n"
    "// bStock (Binance) first: it is also what the Agentic Wallet trades; Ondo otherwise.\n"
    "export const bscProduct=ticker=>{const p=BSC_RESEARCH_PRODUCTS[ticker];return p?.bstock?{platform:'bstock',...p.bstock}:p?.ondo?{platform:'ondo',...p.ondo}:null;};\n")
print(json.dumps({"tickers": len(products), "funds": len(funds), "bstock": sum("bstock" in p for p in products.values()), "out": str(out)}))
