#!/usr/bin/env node
// One source for code the web app and the research worker share.
// 1. The agent rule catalog: engine/agent/xtxc_agent/research/agent_rules.json -> ES module (web + worker).
// 2. Store/profile modules: web/lib is the source; the worker (engine/lib) gets byte-identical copies.
import {copyFileSync, readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root = fileURLToPath(new URL('..', import.meta.url));
const source = 'engine/agent/xtxc_agent/research/agent_rules.json';
export const SHARED = ['research-agent-core.mjs', 'research-store.mjs', 'research-agent-profile.mjs', 'research-agent-suggest.mjs', 'binance-web3.mjs', 'bsc-execution.mjs', 'research-agentic.mjs', 'research-bsc-sell.mjs', 'bsc-research-universe.mjs', 'bsc-research-themes.mjs', 'research-intake.mjs'];
export function catalogModule() {
  const data = JSON.parse(readFileSync(root + source, 'utf8'));
  return `// Generated by dev/sync-shared.mjs from ${source}. Do not edit by hand.\n` +
    `export const AGENT_RULES = ${JSON.stringify(data, null, 1)};\n`;
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  for (const out of ['web/lib/agent-rules.mjs', 'engine/lib/agent-rules.mjs']) writeFileSync(root + out, catalogModule());
  for (const f of SHARED) copyFileSync(root + 'web/lib/' + f, root + 'engine/lib/' + f);
  console.log('agent rules and shared modules synced');
}
