import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {generateKeyPairSync,sign} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {getTransactionDecoder,getTransactionEncoder} from '@solana/kit';
import {DEVNET,MAINNET,STOCKMESH,USDC,TOKEN,COMPUTE,SYSTEM,ALT,keyString,keyBytes,validatePolicy,policyAddress,policyInstruction,policyTransaction,observePolicy,allowOrder,verifyExactSignature,hash} from '../lib/research-autonomy-policy.mjs';
import {AutonomyJournal} from '../lib/research-autonomy-journal.mjs';
import {inspectStockMeshBuy,inspectStockMeshTrade,decodeMessage} from '../lib/research-autonomy-wire.mjs';
import {AutonomyRuntime,verifyMainnetReceipt,PrivyDelegatedSigner,normalizeBuyQuote} from '../lib/research-autonomy-runtime.mjs';
import {getProgramDerivedAddress} from '@solana/kit';
import {MainnetObservationRpc,verifyUnchangedNonce} from '../lib/research-autonomy-rpc.mjs';
const key=n=>keyString(Buffer.alloc(32,n));
const config=()=>({schema:'xtxc.autonomy-policy/v1',executionChain:'solana:mainnet',evidenceChain:'solana:devnet',program:key(191),owner:key(192),verifier:key(193),wallet:key(194),id:'ab'.repeat(32),approvalHash:'cd'.repeat(32),startsAt:'0',expiresAt:'0',buyBudgetAtoms:'3000000',perBuyAtoms:'2000000',maxOrders:'2',mints:[key(195)],maxSlippageBps:20,feeBudgetLamports:null});
const lifetime={blockhash:key(201),lastValidBlockHeight:'9999999'};
const state=()=>({active:true,revoked:false,pending:false,count:'0',reservedAtoms:'0',slot:100,observedAt:Date.now()});
async function observed(c){const {state,bump}=await policyAddress(c),d=Buffer.alloc(616);d.write('XTXCDMP1');for(const [p,k] of [[8,c.owner],[40,c.verifier],[72,c.wallet]])keyBytes(k).copy(d,p);Buffer.from(c.id,'hex').copy(d,104);Buffer.from(c.approvalHash,'hex').copy(d,136);for(const [p,v] of [[168,c.startsAt],[176,c.expiresAt],[184,c.buyBudgetAtoms],[208,c.maxOrders],[216,c.perBuyAtoms]])d.writeBigUInt64LE(BigInt(v),p);d[226]=c.mints.length;d[227]=bump;c.mints.forEach((m,i)=>keyBytes(m).copy(d,344+i*32));return{genesisHash:DEVNET,commitment:'finalized',address:state,owner:c.program,slot:100,observedAt:Date.now(),dataBase64:d.toString('base64')};}
test('policy approval serializes user parameters, not demo steps',async()=>{const c=config();c.buyBudgetAtoms='100000000';c.perBuyAtoms='17000000';c.maxOrders='39';const ix=await policyInstruction(c,'APPROVE');assert.equal(Buffer.from(ix.data).readBigUInt64LE(145),100000000n);assert.equal(Buffer.from(ix.data).readBigUInt64LE(153),17000000n);assert.equal(Buffer.from(ix.data).readBigUInt64LE(161),39n);assert.ok(policyTransaction(c.owner,[ix],lifetime).transactionBase64.length<1644);});
test('2+1 is a scenario; third is rejected because actual limits exhausted',()=>{const c=config(),s=state();allowOrder(c,s,{side:'BUY',mint:c.mints[0],inputAtoms:'2000000'});allowOrder(c,{...s,count:'1',reservedAtoms:'2000000'},{side:'BUY',mint:c.mints[0],inputAtoms:'1000000'});assert.throws(()=>allowOrder(c,{...s,count:'2',reservedAtoms:'3000000'},{side:'BUY',mint:c.mints[0],inputAtoms:'1'}),/ORDER_LIMIT/);c.maxOrders='20';assert.throws(()=>allowOrder(c,{...s,count:'2',reservedAtoms:'3000000'},{side:'BUY',mint:c.mints[0],inputAtoms:'1'}),/BUY_BUDGET_EXHAUSTED/);c.buyBudgetAtoms='20000000';allowOrder(c,{...s,count:'2',reservedAtoms:'3000000'},{side:'BUY',mint:c.mints[0],inputAtoms:'1500000'});});
test('asset, order, pending and revoked limits independently reject',()=>{const c=config(),o={side:'BUY',mint:c.mints[0],inputAtoms:'1'};for(const s of [{...state(),active:false},{...state(),revoked:true},{...state(),pending:true}])assert.throws(()=>allowOrder(c,s,o));for(const o2 of [{...o,mint:key(111)},{...o,inputAtoms:'2000001'},{...o,side:'SELL'}])assert.throws(()=>allowOrder(c,state(),o2));});
test('configuration rejects unsafe integer and invalid time/universe',()=>{for(const patch of [{buyBudgetAtoms:3},{maxOrders:'0'},{startsAt:'10',expiresAt:'9'},{perBuyAtoms:'3000001'},{mints:[config().mints[0],config().mints[0]]},{owner:config().verifier}])assert.throws(()=>validatePolicy({...config(),...patch}));});
test('devnet finalized account binds limits and exact wallet',async()=>{const c=config(),o=await observed(c);assert.equal((await observePolicy(c,o)).count,'0');for(const patch of [{genesisHash:MAINNET},{commitment:'confirmed'},{observedAt:Date.now()-60000},{owner:c.owner}])await assert.rejects(observePolicy(c,{...o,...patch}));for(const p of [72,136,184,208,216,227,344]){const d=Buffer.from(o.dataBase64,'base64');d[p]^=1;await assert.rejects(observePolicy(c,{...o,dataBase64:d.toString('base64')}));}});
test('no implicit one-hour cap; explicit expiry still works',async()=>{const c=config(),o=await observed(c);assert.equal((await observePolicy(c,o)).active,true);c.expiresAt='1';assert.equal((await observePolicy(c,await observed(c))).active,false);});

async function sample(){const pair=generateKeyPairSync('ed25519'),wallet=keyString(pair.publicKey.export({type:'spki',format:'der'}).subarray(-32)),c={...config(),wallet};const nonce=(await getProgramDerivedAddress({programAddress:STOCKMESH,seeds:[Buffer.from('stocklana'),keyBytes(wallet)]}))[0];const ata=async m=>(await getProgramDerivedAddress({programAddress:'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',seeds:[keyBytes(wallet),keyBytes(TOKEN),keyBytes(m)]}))[0];const src=await ata(USDC),dst=await ata(c.mints[0]);const accounts=[wallet,nonce,src,USDC,TOKEN,dst,c.mints[0],key(111)];const d=Buffer.alloc(36+6+14+9);d.set([2,2,1,0]);d.writeBigUInt64LE(2000000n,12);d.writeBigUInt64LE(90n,20);d.writeBigUInt64LE(999999999n,28);d.set([2,3,4,5,6,4],36);d.set([0,0,1,1],42);d.writeBigUInt64LE(2000000n,46);d[54]=7;d[55]=9;d.set([0,2,3,4,5,6,7,2,3],56);const cu=Buffer.from([2,0x40,0x0d,0x03,0]),price=Buffer.alloc(9);price[0]=3;const instructions=[{programAddress:COMPUTE,accounts:[],data:cu},{programAddress:COMPUTE,accounts:[],data:price},{programAddress:STOCKMESH,accounts:accounts.map((address,i)=>({address,role:i===0?3:[1,2,5].includes(i)?1:0})),data:d}];const unsigned=policyTransaction(wallet,instructions,lifetime).transactionBase64;const facts=await inspectStockMeshBuy(unsigned,wallet,{mint:c.mints[0],inputAtoms:'2000000',minimumOutputAtoms:'90'},async()=>{throw Error('unexpected lookup');});const tx=getTransactionDecoder().decode(Buffer.from(unsigned,'base64')),signed=Buffer.from(getTransactionEncoder().encode({...tx,signatures:{[wallet]:sign(null,Buffer.from(tx.messageBytes),pair.privateKey)}})).toString('base64');const prepared={owner:wallet,quoteId:'stkq_test',preparedId:'stkp_test',submitAllowed:true,transactionBase64:unsigned,expiresAt:new Date(Date.now()+120000).toISOString()};return{pair,c,prepared,facts,signed,instructions,wallet};}
test('wire verifier rejects extra transfers and amount or mint changes',async()=>{const x=await sample();for(const changed of [{mint:key(112),inputAtoms:'2000000',minimumOutputAtoms:'90'},{mint:x.c.mints[0],inputAtoms:'2000001',minimumOutputAtoms:'90'}])await assert.rejects(inspectStockMeshBuy(x.prepared.transactionBase64,x.wallet,changed,async()=>null));const ix={programAddress:SYSTEM,accounts:[{address:x.wallet,role:3},{address:key(112),role:1}],data:Buffer.alloc(12)};const wire=policyTransaction(x.wallet,[...x.instructions,ix],lifetime).transactionBase64;await assert.rejects(inspectStockMeshBuy(wire,x.wallet,{mint:x.c.mints[0],inputAtoms:'2000000',minimumOutputAtoms:'90'},async()=>null));});
test('signed exact wire accepts only the approved message and valid signature',async()=>{const x=await sample();assert.ok(verifyExactSignature(x.prepared.transactionBase64,x.signed,x.wallet));const b=Buffer.from(x.signed,'base64');b[8]^=1;assert.throws(()=>verifyExactSignature(x.prepared.transactionBase64,b.toString('base64'),x.wallet));});
function permitted(r,s){return{...s,count:String(BigInt(r.counter)+1n),reservedAtoms:String(BigInt(r.priorReserved)+BigInt(r.facts.inputAtoms)),pending:true,messageHash:r.facts.messageHash,pendingAtoms:r.facts.inputAtoms,pendingMint:r.facts.mint,slot:101};}
test('journal persists before signing, survives restart, never retries uncertain signing',async()=>{const x=await sample(),path=mkdtempSync(join(tmpdir(),'xtxc-autonomy-'));try{let db=new DatabaseSync(join(path,'gate.db')),j=new AutonomyJournal(db);j.register(x.c,state());const r=j.stage(x.c.id,state(),x.prepared,x.facts),s=permitted(r,state());j.permitted(r.id,s,'a'.repeat(88));j.beginSigning(r.id,s);db.close();db=new DatabaseSync(join(path,'gate.db'));j=new AutonomyJournal(db);assert.equal(j.order(r.id).phase,'SIGNING');assert.throws(()=>j.beginSigning(r.id,s),/SIGNING_NOT_ALLOWED/);j.signingUnknown(r.id);assert.throws(()=>j.stage(x.c.id,{...s,pending:false},x.prepared,x.facts),/ORDER_UNRESOLVED/);assert.throws(()=>j.permitted(r.id,s,'a'.repeat(88)));db.close();}finally{rmSync(path,{recursive:true,force:true});}});
test('duplicate relay uses same wire; revoke and devnet reset block',async()=>{const x=await sample(),db=new DatabaseSync(':memory:'),j=new AutonomyJournal(db);j.register(x.c,state());const r=j.stage(x.c.id,state(),x.prepared,x.facts),s=permitted(r,state());j.permitted(r.id,s,'a'.repeat(88));j.beginSigning(r.id,s);j.signed(r.id,x.signed);assert.equal(j.beginRelay(r.id,s).signedTransactionBase64,x.signed);assert.equal(j.beginRelay(r.id,s).relayAttempts,2);assert.throws(()=>j.beginRelay(r.id,state()),/DEVNET_STATE_REGRESSED/);j.stop(x.c.id,x.c.owner);assert.throws(()=>j.beginRelay(r.id,s),/RELAY_NOT_ALLOWED/);db.close();});
test('unsigned expiry is evidence only before any signing attempt, never a refund',async()=>{
 const x=await sample(),db=new DatabaseSync(':memory:'),j=new AutonomyJournal(db);try{
  j.register(x.c,state());const r=j.stage(x.c.id,state(),{...x.prepared,expiresAt:new Date(Date.now()-1000).toISOString()},x.facts),s=permitted(r,state());
  assert.throws(()=>j.expireUnsigned(r.id,state()),/DEVNET_RESERVATION_MISMATCH/);
  const out=j.expireUnsigned(r.id,s);assert.equal(out.phase,'EXPIRED_UNSIGNED');assert.equal(out.receipt.signature,null);assert.equal(j.policy(x.c.id).last_reserved,'2000000');
 }finally{db.close();}
});
test('ambiguous signing cannot be relabeled as unsigned expiry',async()=>{
 const x=await sample(),db=new DatabaseSync(':memory:'),j=new AutonomyJournal(db);try{
  j.register(x.c,state());const r=j.stage(x.c.id,state(),{...x.prepared,expiresAt:new Date(Date.now()-1000).toISOString()},x.facts),s=permitted(r,state());
  j.permitted(r.id,s,'a'.repeat(88));j.beginSigning(r.id,s);j.signingUnknown(r.id);
  assert.throws(()=>j.expireUnsigned(r.id,s),/UNSIGNED_EXPIRY_NOT_PROVEN/);assert.equal(j.order(r.id).phase,'SIGNING_UNKNOWN');
 }finally{db.close();}
});
test('finalized mainnet receipt proves actual debit and delivery, not just a hash',async()=>{const x=await sample(),signature=verifyExactSignature(x.prepared.transactionBase64,x.signed,x.wallet),row={...x,signedTransactionBase64:x.signed,signature};const src=x.facts.keys.indexOf(x.facts.source),dst=x.facts.keys.indexOf(x.facts.destination);const b=(accountIndex,mint,amount)=>({accountIndex,mint,owner:x.wallet,uiTokenAmount:{amount}});const o={genesisHash:MAINNET,status:{confirmationStatus:'finalized',slot:1000,err:null},tx:{slot:1000,transaction:[x.signed,'base64'],meta:{err:null,fee:5000,preTokenBalances:[b(src,USDC,'3000000')],postTokenBalances:[b(src,USDC,'1000000'),b(dst,x.c.mints[0],'100')]}}};assert.equal(verifyMainnetReceipt(row,o).phase,'RECONCILED');o.tx.meta.postTokenBalances[1].uiTokenAmount.amount='1';assert.throws(()=>verifyMainnetReceipt(row,o),/TOKEN_DELIVERY_MISMATCH/);});
test('Privy signing requires exact additional signer and configured policy',async()=>{const c=config(),binding={owner:c.owner,address:c.wallet,walletId:'wallet',signerId:'signer',policyId:'policy',enabled:true};let signed=0;const client={wallets:()=>({get:async()=>({chain_type:'solana',address:c.wallet,additional_signers:[]}),solana:()=>({signTransaction:async()=>{signed++;return{signedTransaction:'x'};}})})};const s=new PrivyDelegatedSigner(client,{},binding);await assert.rejects(s.signTransaction(c,'wire'));assert.equal(signed,0);});
test('real StockMesh exposure schema is converted without token/UI scaling confusion',()=>{const q={schema:'skew.stockmesh.exposure-quote/v2',quoteId:'q',instrument:'NVDA',inputSymbol:'USDC',inAmountAtoms:'2000000',exposure:{estimatedQ32:'100000000',minimumQ32:'99800000',products:[{mint:config().mints[0],rawOutputAtoms:'50000000'}]}};const e={instrument:'NVDA',mint:config().mints[0],inputAtoms:'2000000',maxSlippageBps:20};assert.equal(normalizeBuyQuote(q,e).minimumOutputAtoms,'49900000');assert.throws(()=>normalizeBuyQuote({...q,inputSymbol:'SOL'},e));assert.throws(()=>normalizeBuyQuote({...q,exposure:{...q.exposure,products:[...q.exposure.products,...q.exposure.products]}},e));assert.throws(()=>normalizeBuyQuote(q,{...e,maxSlippageBps:10}));});
test('immutable independent policies coexist; pending transaction lock remains wallet scoped',async()=>{const x=await sample(),c=x.c,db=new DatabaseSync(':memory:'),j=new AutonomyJournal(db);j.register(c,state());assert.throws(()=>j.register({...c,buyBudgetAtoms:'10000000'},state()),/APPROVAL_CHANGED/);const other={...c,id:'de'.repeat(32)};assert.equal(j.register(other,state()).phase,'ACTIVE');j.stage(c.id,state(),x.prepared,x.facts);assert.throws(()=>j.stage(other.id,state(),x.prepared,x.facts),/ORDER_UNRESOLVED/);db.close();});

test('runtime contract: devnet reservation precedes signing and exact mainnet delivery precedes result evidence',async()=>{
 const x=await sample(),db=new DatabaseSync(':memory:'),journal=new AutonomyJournal(db);let observation=await observed(x.c);journal.register(x.c,await observePolicy(x.c,observation));const events=[];let settleFail=true;
 const src=x.facts.keys.indexOf(x.facts.source),dst=x.facts.keys.indexOf(x.facts.destination),balance=(accountIndex,mint,amount)=>({accountIndex,mint,owner:x.wallet,uiTokenAmount:{amount}});
 const signature=verifyExactSignature(x.prepared.transactionBase64,x.signed,x.wallet);
 const mainnet={pin:async()=>{},lookup:async()=>null,simulate:async()=>({genesisHash:MAINNET,messageHash:x.facts.messageHash,err:null}),blockhashValid:async()=>true,transaction:async()=>({genesisHash:MAINNET,status:{confirmationStatus:'finalized',slot:1000,err:null},tx:{slot:1000,transaction:[x.signed,'base64'],meta:{err:null,fee:5000,preTokenBalances:[balance(src,USDC,'3000000')],postTokenBalances:[balance(src,USDC,'1000000'),balance(dst,x.c.mints[0],'100')]}}})};
 const devnet={observe:async()=>observation,reserve:async(c,row)=>{events.push('reserve');const d=Buffer.from(observation.dataBase64,'base64');d.writeBigUInt64LE(2000000n,192);d.writeBigUInt64LE(1n,200);d[224]=1;Buffer.from(row.facts.messageHash,'hex').copy(d,232);d.writeBigUInt64LE(2000000n,264);keyBytes(x.c.mints[0]).copy(d,272);observation={...observation,slot:101,dataBase64:d.toString('base64')};return 'v'.repeat(88);},settle:async(c,row)=>{assert.equal(row.phase,'RECONCILED');events.push('settle');if(settleFail){settleFail=false;throw Error('DEVNET_CONFIRMATION_PENDING');}return 'r'.repeat(88);}};
 const stockmesh={quote:async()=>({schema:'skew.stockmesh.exposure-quote/v2',quoteId:x.prepared.quoteId,instrument:'NVDA',inputSymbol:'USDC',inAmountAtoms:'2000000',exposure:{estimatedQ32:'1000',minimumQ32:'998',products:[{mint:x.c.mints[0],rawOutputAtoms:'90'}]}}),prepare:async()=>x.prepared,submit:async()=>{events.push('submit');return{signature};}};
 stockmesh.order=async()=>({preparedId:x.prepared.preparedId,signature,phase:'RECONCILED',receiptVerified:true});
 const signer={assertBinding:async()=>{},signTransaction:async()=>{events.push('sign');return x.signed;}};
 try{const runtime=new AutonomyRuntime({journal,mainnet,devnet,stockmesh,signer}),r=await runtime.prepare(x.c.id,{instrument:'NVDA',mint:x.c.mints[0],inputAtoms:'2000000'});await assert.rejects(runtime.execute(r.id),/DEVNET_CONFIRMATION_PENDING/);assert.equal(journal.order(r.id).phase,'RECONCILED');assert.deepEqual(events,['reserve','sign','submit','settle']);const restarted=new AutonomyRuntime({journal,mainnet,devnet,stockmesh,signer});const done=await restarted.check(r.id);assert.equal(done.receipt.outputAtoms,'100');assert.equal(done.settlementSignature,'r'.repeat(88));assert.deepEqual(events,['reserve','sign','submit','settle','settle']);await assert.rejects(restarted.execute(r.id));assert.equal(events.filter(e=>e==='sign').length,1);}finally{db.close();}
});

test('SELL exact-wire receipt accounts for stock debit and USDC credit, not BUY units',async()=>{
 const x=await sample(),ix=x.instructions[2],accounts=[...ix.accounts];
 [accounts[2],accounts[5]]=[accounts[5],accounts[2]];
 [accounts[3],accounts[6]]=[accounts[6],accounts[3]];
 const unsigned=policyTransaction(x.wallet,[...x.instructions.slice(0,2),{...ix,accounts}],lifetime).transactionBase64;
 const facts=await inspectStockMeshTrade(unsigned,x.wallet,{side:'SELL',mint:x.c.mints[0],inputAtoms:'2000000',minimumOutputAtoms:'90'},async()=>null);
 const tx=getTransactionDecoder().decode(Buffer.from(unsigned,'base64'));
 const signed=Buffer.from(getTransactionEncoder().encode({...tx,signatures:{[x.wallet]:sign(null,Buffer.from(tx.messageBytes),x.pair.privateKey)}})).toString('base64');
 const row={wallet:x.wallet,prepared:{transactionBase64:unsigned},signedTransactionBase64:signed,signature:verifyExactSignature(unsigned,signed,x.wallet),facts};
 const src=facts.keys.indexOf(facts.source),dst=facts.keys.indexOf(facts.destination),balance=(accountIndex,mint,amount)=>({accountIndex,mint,owner:x.wallet,uiTokenAmount:{amount}});
 const observed={genesisHash:MAINNET,status:{confirmationStatus:'finalized',slot:1000,err:null},tx:{slot:1000,transaction:[signed,'base64'],meta:{err:null,fee:5000,preTokenBalances:[balance(src,x.c.mints[0],'3000000'),balance(dst,USDC,'7')],postTokenBalances:[balance(src,x.c.mints[0],'1000000'),balance(dst,USDC,'107')]}}};
 const receipt=verifyMainnetReceipt(row,observed);
 assert.equal(receipt.side,'SELL');assert.equal(receipt.inputAtoms,'2000000');assert.equal(receipt.outputAtoms,'100');assert.equal(receipt.destinationMint,USDC);
 observed.tx.meta.postTokenBalances[1].uiTokenAmount.amount='96';
 assert.throws(()=>verifyMainnetReceipt(row,observed),/TOKEN_DELIVERY_MISMATCH/);
 await assert.rejects(inspectStockMeshTrade(unsigned,x.wallet,{side:'BUY',mint:x.c.mints[0],inputAtoms:'2000000',minimumOutputAtoms:'90'},async()=>null));
});

test('signed expiry requires exact wire, expired blockhash, absent history and unchanged finalized nonce',async()=>{
 const x=await sample(),signature=verifyExactSignature(x.prepared.transactionBase64,x.signed,x.wallet);
 const row={...x,signedTransactionBase64:x.signed,signature};const d=Buffer.alloc(64);d.write('SKEWSEQ1');keyBytes(x.wallet).copy(d,8);d.writeBigUInt64LE(BigInt(x.facts.nonceSequence),40);
 let value={context:{slot:Number(x.facts.deadlineSlot)+1},value:{owner:STOCKMESH,executable:false,data:[d.toString('base64'),'base64']}};
 let valid=false,status=null;const calls=[];
 const rpc=Object.create(MainnetObservationRpc.prototype);rpc.call=async(method,params)=>{calls.push(method);if(method==='getGenesisHash')return MAINNET;if(method==='isBlockhashValid'){assert.equal(params[1].commitment,'finalized');return{value:valid};}if(method==='getSignatureStatuses')return{value:[status]};if(method==='getAccountInfo'){assert.equal(params[0],x.facts.nonceAddress);assert.equal(params[1].minContextSlot,Number(x.facts.deadlineSlot)+1);return value;}throw Error('forbidden call '+method);};
 const proof=await rpc.expiredNoFill(row);assert.equal(proof.phase,'EXPIRED_NO_FILL');assert.equal(proof.networkFeeStatus,'UNKNOWN');
 valid=true;assert.equal(await rpc.expiredNoFill(row),null);valid=false;status={confirmationStatus:'processed'};assert.equal(await rpc.expiredNoFill(row),null);status=null;
 d.writeBigUInt64LE(BigInt(x.facts.nonceSequence)+1n,40);value.value.data[0]=d.toString('base64');assert.equal(await rpc.expiredNoFill(row),null);
 assert.equal(verifyUnchangedNonce(x.facts,x.wallet,{context:{slot:Number(x.facts.deadlineSlot)},value:value.value}),null);
 assert.equal(verifyUnchangedNonce(x.facts,x.wallet,{context:{slot:Number(x.facts.deadlineSlot)+1},value:null}),null);
 assert.equal(calls.includes('sendTransaction'),false);
});

test('router lock is reconciled after mainnet receipt and before any next leg',async()=>{
 const x=await sample(),db=new DatabaseSync(':memory:'),j=new AutonomyJournal(db);try{
  j.register(x.c,state());let r=j.stage(x.c.id,state(),x.prepared,x.facts);const s=permitted(r,state());j.permitted(r.id,s,'a'.repeat(88));j.beginSigning(r.id,s);r=j.signed(r.id,x.signed);
  j.recordReceipt(r.id,{phase:'RECONCILED',signature:r.signature,messageHash:r.facts.messageHash});let phase='SUBMITTED',settled=0;
  const runtime=new AutonomyRuntime({journal:j,mainnet:{pin:async()=>{}},stockmesh:{order:async()=>({phase,signature:r.signature,receiptVerified:phase==='RECONCILED'})},devnet:{settle:async()=>{settled++;return'settlement';}},signer:{signTransaction:()=>{throw Error('must not sign');}}});
  await assert.rejects(runtime.check(r.id),/STOCKMESH_RECONCILIATION_PENDING/);assert.equal(settled,0);assert.equal(j.order(r.id).engineReconciled,undefined);
  phase='RECONCILED';const done=await runtime.check(r.id);assert.equal(done.engineReconciled.phase,'RECONCILED');assert.equal(settled,1);await runtime.check(r.id);assert.equal(settled,1);
 }finally{db.close();}
});

test('expired signed order is closed without submitting, replacement or refunding its allowance',async()=>{
 const x=await sample(),db=new DatabaseSync(':memory:'),j=new AutonomyJournal(db);try{
  j.register(x.c,state());let r=j.stage(x.c.id,state(),x.prepared,x.facts);const s=permitted(r,state());j.permitted(r.id,s,'a'.repeat(88));j.beginSigning(r.id,s);r=j.signed(r.id,x.signed);r=j.beginRelay(r.id,s);
  const proof={schema:'xtxc.signed-expiry/v1',phase:'EXPIRED_NO_FILL',signature:r.signature,messageHash:r.facts.messageHash,blockhashExpired:true,historyAbsent:true,slot:Number(r.facts.deadlineSlot)+1,reason:'FINALIZED_UNCHANGED_STOCKMESH_NONCE'};
  for(const patch of [{historyAbsent:false},{blockhashExpired:false},{slot:Number(r.facts.deadlineSlot)},{signature:'other'}])assert.throws(()=>j.expireSigned(r.id,{...proof,...patch}),/SIGNED_EXPIRY_NOT_PROVEN/);
  const runtime=new AutonomyRuntime({journal:j,mainnet:{pin:async()=>{},transaction:async()=>null,expiredNoFill:async()=>proof},stockmesh:{order:async()=>null,submit:()=>{throw Error('must not send');}},devnet:{settle:async()=> 'devnet-failed-result'}});
  const done=await runtime.check(r.id);assert.equal(done.phase,'EXPIRED_NO_FILL');assert.equal(done.engineReconciled.phase,'NOT_ADMITTED');assert.equal(done.signature,r.signature);assert.equal(done.relayAttempts,1);assert.equal(j.policy(x.c.id).last_reserved,'2000000');assert.throws(()=>j.beginRelay(r.id,s),/RELAY_NOT_ALLOWED/);
 }finally{db.close();}
});
