import {test} from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,sign,randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import {getBase58Decoder,getTransactionDecoder,getTransactionEncoder}from'@solana/kit';
import{AgentStore}from'../lib/research-agent-core.mjs';
import{AnchorService,DevnetRpc,DEVNET_GENESIS,anchorCanonical,approvalCommitment,buildApprovalWire,verifyApprovalWire,verifyAnchorReceipt}from'../lib/research-anchor.mjs';
const keys=generateKeyPairSync('ed25519'),owner=getBase58Decoder().decode(keys.publicKey.export({format:'der',type:'spki'}).subarray(-32)),address='solana:'+owner;
const lifetime={blockhash:'11111111111111111111111111111111',lastValidBlockHeight:1000};
const salt='ab'.repeat(32),plan={id:'de'.repeat(32),owner:address,budgetAtoms:'100000000',nonce:'fixture'};
function signed(p,k=keys){const tx=getTransactionDecoder().decode(Buffer.from(p.transactionBase64,'base64'));return Buffer.from(getTransactionEncoder().encode({...tx,signatures:{[owner]:sign(null,Buffer.from(tx.messageBytes),k.privateKey)}})).toString('base64');}
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'xtxc-anchor-')),store=new AgentStore(join(dir,'db'),['NVDA']);t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});const strategy=store.mutate(address,{operation:'CREATE',requestId:randomUUID(),brief:{name:'anchor fixture',objective:'Research only',budget:'100',instruments:['NVDA']}});const p={...plan,strategyId:strategy.id};store.db.prepare('INSERT INTO agent_plans VALUES(?,?,?,?,?,?,?)').run(p.id,store.owner(address),strategy.id,'fixture',JSON.stringify(p),'APPROVED',Date.now());const calls=[];let receipt=null,status=null,height=10,timeout=false;
 const rpc={pin:async()=>{},call:async(method,args)=>{calls.push(method);if(method==='getLatestBlockhash')return{value:lifetime};if(method==='getBalance')return{value:50000};if(method==='getFeeForMessage')return{value:5000};if(method==='getBlockHeight')return height;if(method==='sendTransaction'){if(timeout)throw Error('response lost');return verifyApprovalWire(service.rows(address,p.id)[0],args[0]);}if(method==='getSignatureStatuses')return{value:[status]};if(method==='getTransaction')return receipt;throw Error(method);}};
 const service=new AnchorService(store,rpc);return{store,service,p,calls,set(v){({receipt=receipt,status=status,height=height,timeout=timeout}=v);}};}
test('canonicalization is stable, NFC, rejects fractional values',()=>{assert.equal(anchorCanonical({z:'e\u0301',a:1}),'{"a":1,"z":"é"}');assert.equal(approvalCommitment(plan,salt),approvalCommitment({...plan,status:'COMPLETE',steps:[]},salt));assert.notEqual(approvalCommitment(plan,salt),approvalCommitment({...plan,budgetAtoms:'200000000'},salt));assert.throws(()=>anchorCanonical({x:1.1}));});
test('memo wire is owner signed, exact message and no substituted instructions',()=>{const p={...buildApprovalWire(owner,approvalCommitment(plan,salt),lifetime),owner};const wire=signed(p);assert.match(verifyApprovalWire(p,wire),/^[1-9A-HJ-NP-Za-km-z]{80,90}$/);assert.throws(()=>verifyApprovalWire(p,p.transactionBase64));assert.throws(()=>verifyApprovalWire(p,signed(p,generateKeyPairSync('ed25519'))));const other={...buildApprovalWire(owner,'ff'.repeat(32),lifetime),owner};assert.throws(()=>verifyApprovalWire(p,signed(other)));});
test('RPC rejects mainnet and arbitrary methods',async()=>{const rpc=new DevnetRpc(async()=>Response.json({id:1,result:'mainnet'}));await assert.rejects(rpc.pin(),/devnet/);await assert.rejects(rpc.call('requestAirdrop'),/Unsupported/);const ok=new DevnetRpc(async()=>Response.json({id:1,result:DEVNET_GENESIS}));await ok.pin();});
test('prepare idempotency, ownership and restart persistence',async t=>{const f=fixture(t),a=await f.service.prepare(address,f.p.id),b=await f.service.prepare(address,f.p.id);assert.equal(a.id,b.id);assert.equal(a.salt,undefined);assert.equal(a.shortfallLamports,'0');assert.throws(()=>f.service.list('solana:'+'1'.repeat(32),f.p.id));const reopened=new AnchorService(f.store,{});assert.equal(reopened.list(address,f.p.id)[0].id,a.id);});
test('timeout persists exact signature; UNKNOWN is not replaced even after expiry',async t=>{const f=fixture(t),p=await f.service.prepare(address,f.p.id);f.set({timeout:true});const result=await f.service.submit(address,p.id,signed(p));assert.equal(result.phase,'UNKNOWN');assert.ok(result.signature);f.set({height:5000});assert.equal((await f.service.status(address,p.id)).phase,'UNKNOWN');assert.equal((await f.service.prepare(address,f.p.id)).id,p.id);});
test('unsigned expiry requires fresh explicit preparation, no transaction sent',async t=>{const f=fixture(t),p=await f.service.prepare(address,f.p.id);f.set({height:2000});assert.equal((await f.service.status(address,p.id)).phase,'EXPIRED_UNSENT');assert.notEqual((await f.service.prepare(address,f.p.id)).id,p.id);assert.equal(f.calls.includes('sendTransaction'),false);});
test('exact confirmed/finalized receipt, failed and mismatched wire rejected',async t=>{const f=fixture(t),p=await f.service.prepare(address,f.p.id),wire=signed(p),s=await f.service.submit(address,p.id,wire);const row=f.service.get(address,p.id);const tx={transaction:[wire,'base64'],slot:77,meta:{err:null,fee:5000}};const status={confirmationStatus:'confirmed',slot:77,err:null};assert.equal(verifyAnchorReceipt(row,tx,status).type,'ApprovalAnchorReceipt');assert.throws(()=>verifyAnchorReceipt(row,{...tx,slot:76},status));assert.throws(()=>verifyAnchorReceipt(row,{...tx,meta:{err:{InstructionError:[]},fee:5000}},status));f.set({receipt:tx,status});assert.equal((await f.service.status(address,p.id)).phase,'CONFIRMED');f.set({status:{...status,confirmationStatus:'finalized'}});assert.equal((await f.service.status(address,p.id)).phase,'FINALIZED');f.service.put(row,'UNKNOWN');assert.equal(f.service.get(address,p.id).phase,'FINALIZED');});
test('revoked plan cannot submit, existing receipt still inspectable',async t=>{const f=fixture(t),p=await f.service.prepare(address,f.p.id);f.store.revoke(address,f.p.id);await assert.rejects(f.service.submit(address,p.id,signed(p)),/revoked/);assert.equal(f.service.list(address,f.p.id).length,1);});
