import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { AgentStore, allocateBudget, budgetAtoms, validateGoal, checkDelegatedAuthority } from '../lib/research-agent-core.mjs';
import { kilnProposal } from '../lib/research-kiln.mjs';
const owner='solana:'+'1'.repeat(32), other='solana:'+'2'.repeat(32);
const brief={name:'Evidence run',objective:'Compare cost-adjusted strategies.',budget:'100',instruments:['NVDA','AMD'],weights:[],cashBps:null};
const goal={targetReturnBps:1000,horizonDays:365,maxDrawdownBps:2000,maxWeightBps:5000,minCashBps:1000,costBps:50};
function setup(t){const dir=mkdtempSync(join(tmpdir(),'xtxc-agent-test-'));const s=new AgentStore(join(dir,'state.sqlite'),brief.instruments);t.after(()=>{s.close();rmSync(dir,{recursive:true,force:true});});const strategy=s.mutate(owner,{operation:'CREATE',requestId:randomUUID(),brief});return{s,strategy,dir};}
function reviewed(s,strategy,overrides={}){const id=s.enqueue(owner,strategy.id,goal,randomUUID()),run=s.claim();assert.equal(run.id,id);s.finish(run,'REVIEW',{candidates:[{id:'equal_weight',verdict:'ELIGIBLE',weights:[{instrument:'NVDA',weightBps:4500},{instrument:'AMD',weightBps:4500}],...overrides}]});return s.view(owner,strategy.id).runs[0];}
function approve(s,strategy){const r=reviewed(s,strategy);return s.approve(owner,r.id,'equal_weight',r.result.reportHash);}
function prepared(s,p,i){const q={schema:'skew.stockmesh.exposure-quote/v2',quoteId:'fixture',instrument:p.legs[i].instrument,inputSymbol:'USDC',inAmountAtoms:p.legs[i].inputAtoms};const t={owner:owner.slice(7),quoteId:q.quoteId,preparedId:'unsigned-fixture',expiresAt:new Date(Date.now()+60000).toISOString()};s.bindPrepared(owner,p.id,i,t,q);return{q,t};}
test('exact integer budget; no overspend or duplicate instrument',()=>{assert.equal(budgetAtoms('100.01'),'100010000');assert.equal(allocateBudget('101',[{instrument:'A',weightBps:3333},{instrument:'B',weightBps:6666}]).cashAtoms,'1');assert.throws(()=>allocateBudget('10',[{instrument:'A',weightBps:6000},{instrument:'A',weightBps:4000}]));assert.throws(()=>validateGoal({...goal,maxWeightBps:NaN}));});
test('owner isolation, idempotent queue and cancellation fences late worker',t=>{const{s,strategy}=setup(t),request=randomUUID();const id=s.enqueue(owner,strategy.id,goal,request);assert.equal(s.enqueue(owner,strategy.id,goal,request),id);assert.throws(()=>s.enqueue(owner,strategy.id,{...goal,costBps:60},request));assert.throws(()=>s.view(other,strategy.id));const r=s.claim();s.cancel(owner,id);assert.equal(s.finish(r,'REVIEW',{}),false);assert.equal(s.view(owner,strategy.id).runs[0].status,'CANCELLED');});
test('expired worker lease is recoverable and stale worker cannot commit',t=>{const{s,strategy}=setup(t);s.enqueue(owner,strategy.id,goal,randomUUID());const r=s.claim(),recovered=s.claim(Date.now()+310000);assert.equal(recovered.id,r.id);assert.notEqual(recovered.leaseToken,r.leaseToken);assert.equal(s.finish(r,'REVIEW',{}),false);assert.equal(s.finish(recovered,'DECLINED',{}),true);});
test('unavailable dependencies terminate after three attempts and free the owner queue',t=>{
 const{s,strategy}=setup(t);const id=s.enqueue(owner,strategy.id,goal,randomUUID());
 for(let i=0;i<3;i++){const run=s.claim(Date.now()+i*310000);assert.equal(run.id,id);s.finish(run,'WAITING_DATA',null,'WAITING_DATA: Missing verified history for ASML');}
 assert.equal(s.claim(Date.now()+1000000),null);const result=s.view(owner,strategy.id).runs[0];
 assert.equal(result.status,'FAILED');assert.match(result.error,/ASML/);assert.ok(s.enqueue(owner,strategy.id,goal,randomUUID()));
});
test('approval bound to report, brief, eligibility, universe and concentration',t=>{const{s,strategy}=setup(t);const r=reviewed(s,strategy);assert.throws(()=>s.approve(owner,r.id,'equal_weight','altered'));s.mutate(owner,{operation:'UPDATE',id:strategy.id,revision:1,requestId:randomUUID(),brief:{...brief,budget:'200'}});assert.throws(()=>s.approve(owner,r.id,'equal_weight',r.result.reportHash));});
for(const overrides of [{verdict:'DECLINED'},{weights:[{instrument:'FAKE',weightBps:4500}]},{weights:[{instrument:'NVDA',weightBps:6000}]}])test('invalid result cannot create approval '+JSON.stringify(overrides),t=>{const{s,strategy}=setup(t);const r=reviewed(s,strategy,overrides);assert.throws(()=>s.approve(owner,r.id,'equal_weight',r.result.reportHash));});
test('preparation matches real StockMesh quote shape; failed unsigned preparation can retry',t=>{const{s,strategy}=setup(t),p=approve(s,strategy);assert.throws(()=>s.reserveStep(owner,p.id,1));s.reserveStep(owner,p.id,0);s.releaseUnsignedPreparation(owner,p.id,0);s.reserveStep(owner,p.id,0);const{q,t:tx}=prepared(s,p,0);assert.equal(s.reserveStep(owner,p.id,0).existing.preparedId,tx.preparedId);assert.throws(()=>s.bindPrepared(owner,p.id,0,tx,{...q,inAmountAtoms:'999999999'}));});
test('UNKNOWN is not success; revoke cannot erase existing chain outcome',t=>{const{s,strategy}=setup(t),p=approve(s,strategy);s.reserveStep(owner,p.id,0);prepared(s,p,0);s.recordStep(owner,p.id,0,'UNKNOWN');assert.throws(()=>s.reserveStep(owner,p.id,1));assert.equal(s.authorizeSubmit(owner,p.id,0).phase,'UNKNOWN');s.revoke(owner,p.id);assert.throws(()=>s.authorizeSubmit(owner,p.id,0));s.recordStep(owner,p.id,0,'RECONCILED',{signature:'fixture'});assert.equal(s.plan(owner,p.id).status,'REVOKED');assert.equal(s.step(owner,p.id,0).phase,'RECONCILED');});
test('durable plans survive DB reopening and do not resubmit',t=>{const{s,strategy,dir}=setup(t),p=approve(s,strategy);const reopened=new AgentStore(join(dir,'state.sqlite'),brief.instruments);try{assert.equal(reopened.plan(owner,p.id).budgetAtoms,'100000000');assert.equal(reopened.view(owner,strategy.id).plans[0].steps.length,0);}finally{reopened.close();}});
test('model budget reserves uncertain usage and blocks excess',t=>{const{s}=setup(t);const ticket=s.reserveTokens(6000,10000);assert.ok(ticket);assert.equal(s.reserveTokens(6000,10000),null);s.tokenResult(ticket,null);assert.equal(s.reserveTokens(5000,10000),null);});
test('wallet login is never a trading mandate',()=>{assert.throws(()=>checkDelegatedAuthority({verifiedByWalletAdapter:false},{},{ }));});
test('agent-wallet claim excludes simultaneous manual execution and replacement policies',t=>{const{s,strategy}=setup(t),p=approve(s,strategy);s.claimAutonomy(owner,p.id,'a'.repeat(64));s.claimAutonomy(owner,p.id,'a'.repeat(64));assert.throws(()=>s.reserveStep(owner,p.id,0),/agent wallet/);assert.throws(()=>s.claimAutonomy(owner,p.id,'b'.repeat(64)));assert.equal(s.view(owner,strategy.id).plans[0].executionMode,'AGENT_WALLET');});
test('manual reservation prevents claiming the same allocation for an agent wallet',t=>{const{s,strategy}=setup(t),p=approve(s,strategy);s.reserveStep(owner,p.id,0);assert.throws(()=>s.claimAutonomy(owner,p.id,'a'.repeat(64)),/unused allocation/);});
// Approvals are plan-local since the 2026-09-30 release (the signer serializes wallet transactions instead).
// A new approval must still never erase or advance a revoked plan's unresolved outcome.
for(const phase of ['UNKNOWN','SUBMITTED','FINALIZED'])test('a new approval never erases a revoked plan\'s '+phase+' outcome',t=>{
 const{s,strategy}=setup(t),p=approve(s,strategy);s.reserveStep(owner,p.id,0);prepared(s,p,0);s.recordStep(owner,p.id,0,phase);s.revoke(owner,p.id);
 const r=reviewed(s,strategy),next=s.approve(owner,r.id,'equal_weight',r.result.reportHash);
 assert.notEqual(next.id,p.id);assert.equal(s.step(owner,p.id,0).phase,phase);
 assert.throws(()=>s.reserveStep(owner,p.id,1),/no longer current/);assert.throws(()=>s.authorizeSubmit(owner,p.id,0),/no longer valid/);
});
test('revocation during quote prevents late prepared transaction from entering a plan',t=>{const{s,strategy}=setup(t),p=approve(s,strategy);s.reserveStep(owner,p.id,0);s.revoke(owner,p.id);assert.throws(()=>prepared(s,p,0),/changed during preparation/);});
test('holdings review draft binds owner, report, exact sell mint and idempotent allocation',t=>{const{s,strategy}=setup(t),r=reviewed(s,strategy);const allocation={expiresAt:Date.now()+60000,legs:[{side:'SELL',instrument:'NVDA',productMint:'exact-mint',inputAtoms:'200',inputDecimals:6,minimumCashAtoms:'100'}],cashAtoms:'100',cashFloorAtoms:'100',heldValueAtoms:'200',portfolioValueAtoms:'100000200',snapshot:{balanceHash:'fixture'}};
 const draft=s.saveRebalanceDraft(owner,r.id,'equal_weight',r.result.reportHash,allocation);assert.throws(()=>s.approve(other,r.id,'equal_weight',r.result.reportHash,draft.id));const p=s.approve(owner,r.id,'equal_weight',r.result.reportHash,draft.id);assert.equal(p.id,s.approve(owner,r.id,'equal_weight',r.result.reportHash,draft.id).id);assert.equal(p.budgetScope,'SELECTED_HOLDINGS_PLUS_NEW_CASH');s.reserveStep(owner,p.id,0);
 const quote={schema:'skew.stockmesh.liquidation-quote/v1',quoteId:'sell-fixture',instrument:'NVDA',side:'SELL',inputProduct:{mint:'foreign-mint',inputAtoms:'200'},output:{symbol:'USDC',minimumAtoms:'100'}};
 const tx={owner:owner.slice(7),quoteId:'sell-fixture',preparedId:'sell-unsigned',expiresAt:new Date(Date.now()+60000).toISOString()};assert.throws(()=>s.bindPrepared(owner,p.id,0,tx,quote));quote.inputProduct.mint='exact-mint';s.bindPrepared(owner,p.id,0,tx,quote);assert.equal(s.step(owner,p.id,0).phase,'PREPARED');
});
test('Kiln rejects absent models, tool/code proposals and never leaks raw responses',async t=>{const{s,strategy}=setup(t),config={KILN_API_KEY:'test-only-not-a-secret',KILN_BASE_URL:'https://api.bricksum.com/v1',KILN_MODEL_ID:'qwen3-32b'};const input={strategy,goal};await assert.rejects(kilnProposal(input,config,s,async()=>Response.json({data:[]})),/not available/);let n=0;await assert.rejects(kilnProposal(input,config,s,async()=>Response.json(n++?{usage:{prompt_tokens:10,completion_tokens:10},choices:[{message:{content:JSON.stringify({rebalance:'weekly',lookback:63,rationale:'x',execute:'bad'})}}]}:{data:[{id:'qwen3-32b'}]})),/invalid research proposal/);});
