'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import XtxcWordmark from '../../xtxc-wordmark';
import { bnbHref, bnbLocation } from '@/lib/bnb-location';
import { BNB_PAGE_SIZE, parseBnbPage, bnbCompanyName, type BnbInstrument, type BnbInstrumentPage, type BnbProduct } from '@/lib/bnb-market-directory';
import type { ExchangeLocation, ExchangeView } from '@/lib/exchange-location';
import type { GeckoMarket } from '@/lib/bnb-gecko.mjs';
import { Icon, Logo, issuerName, money } from './bnb-parts';
import { BSC_RESEARCH_NAMES, BSC_RESEARCH_STOCKS } from '@/lib/bsc-research-universe.mjs';
import type { StockDirectoryRow } from '@/lib/stock-directory';
import '../stocks-prototype.css';
import '../stocks-workspace.css';
import '../exchange-header.css';
import './bnb-workspace.css';
const Chart=dynamic(()=>import('./bnb-chart'),{loading:()=> <div className="bnb-chart-empty">Opening chart…</div>});
// STA research (custom agents, backtests, approvals) on BNB Chain: the same workspace as Solana,
// with an EVM wallet session, the BSC Ondo/bStock universe and BNB Chain execution.
const Research=dynamic(()=>import('../research-workspace'),{loading:()=> <div className="bnb-view-loading">Opening research…</div>});
// Read-only recorded runs for visitors without a wallet (?view=research&demo=1).
const ResearchDemo=dynamic(()=>import('../research-demo'),{loading:()=> <div className="bnb-view-loading">Opening the demo…</div>});
type Provider={request:(p:{method:string;params?:unknown[]})=>Promise<unknown>;on?:(e:string,f:(...args:unknown[])=>void)=>void;removeListener?:(e:string,f:(...args:unknown[])=>void)=>void;};
const provider=()=>(window as unknown as {ethereum?:Provider}).ethereum;
const WATCH='xtxc.bnb.watchlist.v1';
const address=(v:unknown):v is string=>typeof v==='string'&&/^0x[a-fA-F0-9]{40}$/.test(v);
function units(raw:bigint,decimals:number){const value=raw.toString().padStart(decimals+1,'0');return decimals?`${value.slice(0,-decimals)}.${value.slice(-decimals).replace(/0+$/,'')||'0'}`:value;}
export default function BnbWorkspace({initialLocation,initialPage,featured}:{initialLocation:ExchangeLocation;initialPage:BnbInstrumentPage|null;featured:BnbInstrumentPage[]}){
  const [location,setLocation]=useState(initialLocation),[page,setPage]=useState(initialPage),[query,setQuery]=useState(initialLocation.q??''),[offset,setOffset]=useState(0),[loading,setLoading]=useState(false),[failed,setFailed]=useState(!initialPage),[retry,setRetry]=useState(0);
  const [known,setKnown]=useState<BnbInstrumentPage[]>([]),[watch,setWatch]=useState<string[]>([]),[watchOnly,setWatchOnly]=useState(false),[modal,setModal]=useState(false),[mobileList,setMobileList]=useState(false);
  const [focusId,setFocusId]=useState(initialLocation.instrument??featured.flatMap(p=>p.instruments).find(i=>i.ticker===(initialLocation.stock??'NVDA'))?.id??'');
  const [productId,setProductId]=useState(''),[side,setSide]=useState('Buy'),[amount,setAmount]=useState(''),[researchSeed,setResearchSeed]=useState('');
  const [needsBsc,setNeedsBsc]=useState(false);
  const [demo,setDemo]=useState<boolean|null>(null);
  useEffect(()=>{const read=()=>setDemo(new URLSearchParams(window.location.search).get('demo')==='1');read();window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read);},[]);
  const [wallet,setWallet]=useState<string|null>(null),[walletNetwork,setWalletNetwork]=useState<string|null>(null),[connecting,setConnecting]=useState(false),[notice,setNotice]=useState('');
  const [balances,setBalances]=useState<Record<string,string>>({}),[balanceOwner,setBalanceOwner]=useState(''),[balanceBusy,setBalanceBusy]=useState(false),[balanceAt,setBalanceAt]=useState('');
  const [observations,setObservations]=useState<Record<string,GeckoMarket>>({});
  const search=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null),walletDialog=useRef<HTMLDialogElement>(null),initial=useRef(true),generation=useRef(0),accountRef=useRef<string|null>(null);
  const researchDirectory=useMemo<StockDirectoryRow[]>(()=>BSC_RESEARCH_STOCKS.map(t=>({instrument:t,name:[...featured.flatMap(p=>p.instruments)].find(i=>i.ticker===t)?.names[0]??BSC_RESEARCH_NAMES[t]??t,aliases:[],kinds:['STOCK'],productCount:1,networks:['bnb'],quoteBindings:[],presentationId:null})),[featured]);
  const instruments=useMemo(()=>[...new Map([...featured.flatMap(p=>p.instruments),...known.flatMap(p=>p.instruments),...(page?.instruments??[])].map(i=>[i.id,i])).values()],[featured,known,page]);
  const products=useMemo(()=>[...new Map([...featured.flatMap(p=>p.products),...known.flatMap(p=>p.products),...(page?.products??[])].map(p=>[p.id,p])).values()],[featured,known,page]);
  const focus=instruments.find(i=>i.id===focusId)??instruments[0];
  const focusProducts=products.filter(p=>p.underlyingId===focus?.id);
  const token=focusProducts.find(p=>p.id===productId)??focusProducts.find(p=>p.issuer==='ondo')??focusProducts[0];
  const tokenFor=(id:string)=>products.find(p=>p.underlyingId===id&&p.issuer==='xstocks')??products.find(p=>p.underlyingId===id);
  const starred=instruments.filter(i=>watch.includes(i.id));
  useEffect(()=>{try{const list=JSON.parse(localStorage.getItem(WATCH)??'null');setWatch(Array.isArray(list)?list.filter((s:unknown)=>typeof s==='string').slice(0,200):featured.flatMap(p=>p.instruments).slice(0,4).map(i=>i.id));}catch{}},[featured]);
  useEffect(()=>{
    if(initial.current&&initialPage){initial.current=false;return;}initial.current=false;
    const controller=new AbortController();setLoading(true);setFailed(false);
    const timer=setTimeout(()=>{void fetch(`/api/bnb/instruments?${new URLSearchParams({q:query.trim(),offset:String(offset),limit:String(BNB_PAGE_SIZE)})}`,{signal:controller.signal})
      .then(async r=>{if(!r.ok)throw Error('Catalog unavailable');return parseBnbPage(await r.json());})
      .then(p=>{if(!controller.signal.aborted){setPage(p);setKnown(v=>[...v,p].slice(-24));}})
      .catch(()=>{if(!controller.signal.aborted)setFailed(true);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},160);
    return()=>{controller.abort();clearTimeout(timer);};
  },[query,offset,retry,initialPage]);
  const onObservation=useCallback((observation:GeckoMarket)=>setObservations(v=>({...v,[observation.contract]:observation})),[]);
  const [binancePrices,setBinancePrices]=useState<Record<string,number>>({});
  const onBinancePrice=useCallback((contract:string,price:number)=>setBinancePrices(v=>v[contract]===price?v:{...v,[contract]:price}),[]);
  function navigate(view:ExchangeView,item?:BnbInstrument){
    const next:ExchangeLocation={chain:'bnb',network:'mainnet',view:view==='markets'?'stocks':view,...(item?{stock:item.ticker,instrument:item.id}:{})};
    setLocation(next);setDemo(false);if(item){setFocusId(item.id);setProductId('');setAmount('');}setMobileList(false);setModal(false);window.history.pushState({},'',bnbHref(next));window.scrollTo(0,0);
  }
  function select(item:BnbInstrument){setFocusId(item.id);setProductId('');setModal(false);if(location.view!=='research')navigate('stocks',item);}
  function openSearch(){setModal(true);}
  useEffect(()=>{if(modal){dialog.current?.showModal();requestAnimationFrame(()=>search.current?.focus());}else dialog.current?.close();},[modal]);
  useEffect(()=>{const back=()=>{const next=bnbLocation(Object.fromEntries(new URLSearchParams(window.location.search)));setLocation(next);if(next.instrument)setFocusId(next.instrument);else if(next.stock){const found=instruments.find(i=>i.ticker===next.stock);if(found)setFocusId(found.id);}};
    const keys=(e:KeyboardEvent)=>{const t=e.target as HTMLElement;if(e.key==='/'&&!e.metaKey&&!e.ctrlKey&&!e.altKey&&!t.isContentEditable&&!['INPUT','TEXTAREA','SELECT'].includes(t.tagName)){e.preventDefault();setModal(true);}};
    window.addEventListener('popstate',back);window.addEventListener('keydown',keys);return()=>{window.removeEventListener('popstate',back);window.removeEventListener('keydown',keys);};},[instruments]);
  useEffect(()=>{const p=provider();if(!p)return;const changed=(value:unknown)=>{generation.current++;const accounts=Array.isArray(value)?value:[];const owner=address(accounts[0])?accounts[0]:null;accountRef.current=owner;setWallet(owner);setBalances({});setBalanceOwner('');setBalanceBusy(false);};const chain=(value:unknown)=>{generation.current++;setWalletNetwork(typeof value==='string'?value:null);setBalances({});setBalanceOwner('');setBalanceBusy(false);};p.on?.('accountsChanged',changed);p.on?.('chainChanged',chain);return()=>{p.removeListener?.('accountsChanged',changed);p.removeListener?.('chainChanged',chain);};},[]);
  function toggleWatch(id:string){const next=watch.includes(id)?watch.filter(i=>i!==id):[...watch,id].slice(-200);setWatch(next);try{localStorage.setItem(WATCH,JSON.stringify(next));}catch{setNotice('Watchlist saved for this visit.');}}
  async function connect(){if(wallet){walletDialog.current?.showModal();return;}const p=provider();if(!p){setNotice('Open XTXC in your EVM wallet browser or enable your wallet extension.');return;}setConnecting(true);setNotice('');try{const accounts=await p.request({method:'eth_requestAccounts'}),chain=await p.request({method:'eth_chainId'});if(!Array.isArray(accounts)||!address(accounts[0]))throw Error();accountRef.current=accounts[0];setWallet(accounts[0]);setWalletNetwork(String(chain));}catch{setNotice('Wallet connection was not completed.');}finally{setConnecting(false);}}
  async function refreshBalances(){if(!wallet){void connect();return;}const p=provider();if(!p||balanceBusy)return;const owner=wallet,sequence=++generation.current;setBalanceBusy(true);setNotice('');try{
    const chain=await p.request({method:'eth_chainId'});if(chain!=='0x38'){setNeedsBsc(true);setNotice('Your wallet is on another network. Switch to BNB Chain to read balances and trade.');return;}setNeedsBsc(false);
    const tracked=products.filter(p=>watch.includes(p.underlyingId)||p.underlyingId===focusId).slice(0,64),result:Record<string,string>={};
    const native=await p.request({method:'eth_getBalance',params:[owner,'latest']});if(typeof native!=='string'||!/^0x[a-f0-9]+$/i.test(native))throw Error();result.BNB=units(BigInt(native),18);
    for(let n=0;n<tracked.length;n+=4){if(sequence!==generation.current)return;await Promise.all(tracked.slice(n,n+4).map(async t=>{const raw=await p.request({method:'eth_call',params:[{to:t.contract,data:`0x70a08231${owner.slice(2).toLowerCase().padStart(64,'0')}`},'latest']});if(typeof raw==='string'&&/^0x[a-f0-9]{1,64}$/i.test(raw))result[t.contract]=units(BigInt(raw),t.decimals);}));}
    if(sequence===generation.current&&accountRef.current===owner){setBalances(result);setBalanceOwner(owner);setBalanceAt(new Date().toISOString());}
  }catch{if(sequence===generation.current)setNotice('Balances could not be refreshed. Try again.');}finally{if(sequence===generation.current)setBalanceBusy(false);}}
  const observedBalances=balanceOwner===wallet?balances:{};
  function stockRow(item:BnbInstrument){const p=tokenFor(item.id),observation=products.filter(p=>p.underlyingId===item.id).map(p=>observations[p.contract]).find(Boolean);return <button key={item.id} className={`watch-row ${item.id===focus?.id?'selected':''}`} onClick={()=>select(item)}><Logo key={p?.id??item.id} product={p} ticker={item.ticker}/><span className="watch-name"><b>{item.ticker}</b><small>{bnbCompanyName(item)}</small></span>{observation&&<span className="watch-price">{money(observation.priceUsd)}</span>}</button>;}
  const visible=watchOnly?starred:query?page?.instruments??[]:offset?page?.instruments??[]:instruments.slice(0,68);
  // Asks the wallet to switch (or first add) BNB Smart Chain; the wallet shows its own confirmation.
  async function switchToBsc(){const p=provider();if(!p)return;
    try{await p.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x38'}]});}
    catch(e){if((e as {code?:number})?.code!==4902){setNotice('The wallet did not switch networks. Choose BNB Chain in your wallet.');return;}
      try{await p.request({method:'wallet_addEthereumChain',params:[{chainId:'0x38',chainName:'BNB Smart Chain',nativeCurrency:{name:'BNB',symbol:'BNB',decimals:18},rpcUrls:['https://bsc-dataseed.bnbchain.org'],blockExplorerUrls:['https://bscscan.com']}]});}
      catch{setNotice('The wallet did not add BNB Chain. Add it in your wallet settings.');return;}}
    setNeedsBsc(false);setNotice('');setWalletNetwork('0x38');void refreshBalances();}
  const commonNotice=notice&&<div className="bnb-inline-notice" role="status"><span>{notice}</span>{needsBsc&&<button className="secondary" onClick={()=>void switchToBsc()}>Switch to BNB Chain</button>}<button aria-label="Dismiss" onClick={()=>setNotice('')}><Icon name="close"/></button></div>;
  function research(idea=''){setResearchSeed(idea);navigate('research');}
  return <div className={`xtxc-stocks bnb-only ${location.view==='research'?'is-research':''}`} data-public-network="bnb">
    <header className="topbar exchange-topbar" data-exchange-chain="bnb">
      <a className="xtxc-brand" href="/exchange" aria-label="XTXC home" onClick={e=>{if(!e.metaKey&&!e.ctrlKey){e.preventDefault();navigate('home');}}}><XtxcWordmark/></a>
      <nav aria-label="Main navigation">{(['home','stocks','research','portfolio'] as const).map(view=><a key={view} href={bnbHref({view})} className={`nav-link ${location.view===view||location.view==='markets'&&view==='stocks'?'active':''}`} aria-current={location.view===view?'page':undefined} onClick={e=>{if(!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&!e.altKey){e.preventDefault();navigate(view);}}}>{view==='stocks'?'Markets':view[0].toUpperCase()+view.slice(1)}</a>)}</nav>
      <button className="search-trigger" onClick={openSearch} aria-label="Search stocks and ETFs"><Icon name="search"/><span>Search stocks and ETFs</span><kbd>/</kbd></button>
      <button className="account-button" disabled={connecting} onClick={()=>void connect()}><span className={`account-dot ${wallet?'connected':''}`}/><span>{wallet?`${wallet.slice(0,5)}…${wallet.slice(-4)}`:connecting?'Connecting':'Connect wallet'}</span></button>
    </header>
    {commonNotice}
    {location.view==='research'&&demo!==false?demo?<ResearchDemo/>:<div className="bnb-view-loading">Opening research…</div>
    :location.view==='research'?<Research wallet={wallet} directory={researchDirectory} holdingsNote="BNB Chain balances are on the Portfolio page. Trades from this research appear under Trades." portfolio={null} balanceError={null} orders={[]} historyError={null} onConnect={connect} onSelect={(t:string)=>{const item=instruments.find(i=>i.ticker===t);if(item)select(item);}} onRefresh={()=>void refreshBalances()} onHistory={async()=>{}}/>
    :location.view==='home'?<main className="bnb-home"><div className="bnb-home-heading"><div><span className="bnb-eyebrow">YOUR MARKET</span><h1>Home</h1></div><button className="secondary" onClick={()=>research()}>New research <Icon name="plus"/></button></div>
      <div className="bnb-home-layout"><div><section className="bnb-home-feature"><div><span className="bnb-eyebrow">RESEARCH</span><h2>Start with an idea.</h2><p>Your stocks, your budget, your point of view.</p><button onClick={()=>research()}>Open workspace <Icon name="arrow"/></button></div><div className="bnb-logo-orbit" aria-hidden="true">{instruments.slice(0,5).map(item=><Logo key={item.id} ticker={item.ticker} product={tokenFor(item.id)}/>)}</div></section>
        <div className="section-heading bnb-home-section"><h2>Stocks on your radar</h2><button onClick={()=>navigate('stocks')}>Explore markets <Icon name="arrow"/></button></div>
        <div className="bnb-stock-cards">{featured.flatMap(p=>p.instruments).slice(0,8).map(item=><button key={item.id} className="bnb-stock-card" onClick={()=>navigate('stocks',item)}><div><Logo ticker={item.ticker} product={tokenFor(item.id)}/><Icon name="arrow"/></div><b>{item.ticker}</b><span>{bnbCompanyName(item)}</span><small>{products.filter(p=>p.underlyingId===item.id).map(issuerName).join(' · ')}</small></button>)}</div>
        <div className="section-heading bnb-home-section"><h2>Explore a theme</h2></div><div className="bnb-themes">{[{title:'AI & semiconductors',text:'NVDA · AMD · AVGO',brief:'Compare semiconductor stocks and broad market ETFs, accounting for risk and trading costs.'},{title:'The broader market',text:'SPY · QQQ · VTI',brief:'Explore a diversified portfolio of broad market ETFs.'},{title:'Your own mix',text:'Start from a blank canvas',brief:''}].map(theme=><button key={theme.title} onClick={()=>research(theme.brief)}><b>{theme.title}</b><span>{theme.text}</span><Icon name="arrow"/></button>)}</div>
      </div><aside className="bnb-home-aside"><div className="section-heading"><h2>Watchlist</h2><button aria-label="Add to watchlist" onClick={openSearch}><Icon name="plus"/></button></div>{starred.slice(0,7).map(stockRow)}<button className="text-link" onClick={()=>{setWatchOnly(true);navigate('stocks');}}>View watchlist <Icon name="arrow"/></button><div className="bnb-home-portfolio"><Icon name="wallet"/><h3>Your portfolio</h3><p>{wallet?'Your wallet. Your stock tokens.':'Keep your holdings in view.'}</p><button className="secondary" onClick={()=>navigate('portfolio')}>Open portfolio</button></div></aside></div>
    </main>
    :location.view==='portfolio'?<main className="page bnb-portfolio"><div className="page-heading"><div><h1>Portfolio</h1><p>Your BNB Chain wallet</p></div><button className="secondary" onClick={()=>void refreshBalances()} disabled={balanceBusy}>{balanceBusy?'Refreshing…':'Refresh balances'}</button></div>
      {!wallet?<div className="bnb-portfolio-empty"><Icon name="wallet"/><h2>Your stocks, together.</h2><p>Connect your BNB wallet to view tracked stock tokens.</p><button className="primary" onClick={()=>void connect()}>Connect wallet</button></div>:<><div className="bnb-portfolio-wallet"><span>{wallet}</span><span>BNB balance <b>{observedBalances.BNB??'—'}</b></span></div><div className="section-heading"><h2>Tracked stocks</h2><button onClick={openSearch}>Add a stock <Icon name="plus"/></button></div><p className="bnb-scope-caption">Selected stock and watchlist tokens only.{balanceAt?` Updated ${new Date(balanceAt).toLocaleTimeString()}.`:''}</p><div className="bnb-holdings-table"><div className="bnb-holdings-head"><span>Stock</span><span>Token</span><span>Balance</span></div>{products.filter(p=>watch.includes(p.underlyingId)||p.underlyingId===focusId).map(p=><button key={p.id} onClick={()=>{const item=instruments.find(i=>i.id===p.underlyingId);if(item)navigate('stocks',item);}}><span><Logo product={p} ticker={p.ticker}/><b>{p.ticker}</b></span><span>{p.tokenSymbol}</span><span>{observedBalances[p.contract]??'—'}</span></button>)}</div></>}
    </main>
    :<main className={`workspace ${mobileList?'bnb-sidebar-open':''}`}><aside className="sidebar" aria-label="Stock directory"><div className="sidebar-title"><span>Markets</span><button className="icon-button" aria-label="Find a stock" onClick={openSearch}><Icon name="plus"/></button></div><div className="side-tabs"><button className={`side-tab ${!watchOnly?'active':''}`} onClick={()=>setWatchOnly(false)}>Markets</button><button className={`side-tab ${watchOnly?'active':''}`} onClick={()=>setWatchOnly(true)}>Watchlist</button></div>
      <label className="bnb-sidebar-search"><Icon name="search"/><input placeholder="Find a stock" aria-label="Filter market list" value={query} onChange={e=>{setQuery(e.target.value.slice(0,100));setOffset(0);setWatchOnly(false);}}/></label><div className="bnb-directory-count" role="status">{loading?'Finding stocks…':failed?'Unable to load catalog':`${(watchOnly?starred.length:page?.total??0).toLocaleString()} stocks & ETFs`}</div>
      <div className="bnb-directory-list">{failed?<button className="secondary" onClick={()=>setRetry(n=>n+1)}>Reload markets</button>:visible.map(stockRow)}{!failed&&!loading&&!visible.length&&<p className="bnb-scope-caption">No matching stocks.</p>}</div>
      {!watchOnly&&<div className="bnb-directory-pages"><button disabled={offset===0||loading} onClick={()=>setOffset(n=>Math.max(0,n-BNB_PAGE_SIZE))}>Previous</button><span>{Math.floor(offset/BNB_PAGE_SIZE)+1}</span><button disabled={loading||offset+(page?.instruments.length??0)>=(page?.total??0)} onClick={()=>setOffset(n=>n+BNB_PAGE_SIZE)}>Next</button></div>}
      <div className="sidebar-bottom"><span className="label">Your portfolio</span><strong>{wallet?'Connected':'Not connected'}</strong><button className="text-link" onClick={()=>navigate('portfolio')}>View portfolio <Icon name="arrow"/></button></div>
    </aside><section className="trading-area">{focus&&token?<><div className="market-head"><div className="market-identity"><Logo key={token.id} ticker={focus.ticker} product={tokenFor(focus.id)}/><div><h1>{bnbCompanyName(focus)}</h1><div className="company-meta">{focus.ticker} · BNB Chain</div></div></div><div className="head-controls"><button className="bnb-market-picker" onClick={()=>setMobileList(v=>!v)}>Markets</button><button className="icon-button" aria-label={watch.includes(focus.id)?'Remove from watchlist':'Add to watchlist'} aria-pressed={watch.includes(focus.id)} onClick={()=>toggleWatch(focus.id)}><Icon name="star"/></button><span className="bnb-stock-badge">Stock</span></div></div>
      <div className="trade-layout"><div className="market-content"><Chart key={token.id} product={token} onObservation={onObservation} onBinancePrice={onBinancePrice}/>
        <details className="bnb-token-details"><summary>Token details <span>{token.tokenSymbol}</span></summary><dl><div><dt>Issuer</dt><dd>{issuerName(token)}</dd></div><div><dt>Network</dt><dd>BNB Chain</dd></div><div><dt>Contract</dt><dd><a href={`https://bscscan.com/token/${token.contract}`} target="_blank" rel="noreferrer">{token.contract.slice(0,10)}…{token.contract.slice(-8)} ↗</a></dd></div>{token.issuerEvidence?.underlyingISIN&&<div><dt>Underlying ISIN</dt><dd>{token.issuerEvidence.underlyingISIN}</dd></div>}</dl></details>
        <section className="holding-section section-rule"><div className="section-heading"><h2>Your {focus.ticker}</h2><button onClick={()=>navigate('portfolio')}>View portfolio <Icon name="arrow"/></button></div>{wallet?<p className="muted">{observedBalances[token.contract]??'Refresh portfolio to read your balance.'}{observedBalances[token.contract]!==undefined?` ${token.tokenSymbol}`:''}</p>:<button className="text-link" onClick={()=>void connect()}>Connect wallet to view holdings <Icon name="arrow"/></button>}</section>
      </div><aside className="order-panel" aria-label={`${side} ${bnbCompanyName(focus)}`}><div className="order-top">{['Buy','Sell'].map(s=><button key={s} className={s===side?'active':''} onClick={()=>{setSide(s);setAmount('');}}>{s}</button>)}</div><div className="ticket-body"><h2 className="ticket-title">{side} {bnbCompanyName(focus)}</h2><div className="ticket-subtype"><span>Token</span><select aria-label="Stock token issuer" value={token.id} onChange={e=>{setProductId(e.target.value);setAmount('');}}>{focusProducts.map(p=><option key={p.id} value={p.id}>{p.tokenSymbol} · {issuerName(p)}</option>)}</select></div>
        <label className="input-card bnb-amount-card"><span className="input-label">{side==='Buy'?'You pay':'You sell'}<span>{side==='Buy'?'USDT':token.tokenSymbol}</span></span><span className="money-input"><span>{side==='Buy'?'$':''}</span><input aria-label="Order amount" inputMode="decimal" placeholder="0" value={amount} onChange={e=>{if(/^\d*\.?\d{0,8}$/.test(e.target.value)&&e.target.value.length<=24)setAmount(e.target.value);}}/></span></label><div className="presets">{['10','100','500'].map(n=><button key={n} onClick={()=>setAmount(n)}>{side==='Buy'?'$':''}{n}</button>)}</div>
        <dl className="ticket-summary"><div className="summary-row"><dt>Network</dt><dd>BNB Chain</dd></div><div className="summary-row"><dt>Reference price</dt><dd>{money(observations[token.contract]?.priceUsd??binancePrices[token.contract])}</dd></div></dl>
        <button className="primary wide" onClick={()=>research(`${side} ${amount||'a position in'} ${side==='Buy'?'USDT of ':''}${focus.ticker}. Compare the cost and risk before trading.`)}>Add to research</button><p className="ticket-note">On BNB Chain, trades run from research: your agent tests the idea first, then you approve each swap.</p>
      </div></aside></div>
      <section className="watch-bottom"><div className="section-heading"><h2>On your radar</h2><button onClick={openSearch}>Explore stocks <Icon name="arrow"/></button></div><div className="related-grid">{instruments.filter(i=>i.id!==focus.id).slice(0,3).map(item=><button key={item.id} className="related-stock" onClick={()=>navigate('stocks',item)}><Logo ticker={item.ticker} product={tokenFor(item.id)}/><span><b>{item.ticker}</b><small>{bnbCompanyName(item)}</small></span><Icon name="arrow"/></button>)}</div></section>
    </>:<div className="bnb-view-loading"><h2>{failed?'Markets could not load':'Loading stocks…'}</h2>{failed&&<button className="secondary" onClick={()=>setRetry(n=>n+1)}>Try again</button>}</div>}</section></main>}
    <footer className="statusbar"><span className="bnb-network-label"><img src="/chain-marks/bnb.svg" width="12" height="12" alt=""/>BNB Chain</span><span>Stocks & ETFs</span><a className="footer-end" href="/terms">Terms</a></footer>
    <dialog ref={dialog} className="bnb-search-dialog" aria-label="Search stocks and ETFs" onClose={()=>setModal(false)} onClick={e=>{if(e.currentTarget===e.target)setModal(false);}}><div><Icon name="search"/><input ref={search} aria-label="Search all BNB stocks" placeholder="Company, ticker or token" value={query} onChange={e=>{setQuery(e.target.value.slice(0,100));setOffset(0);}}/><button aria-label="Close search" onClick={()=>setModal(false)}><Icon name="close"/></button></div><p role="status">{loading?'Finding stocks…':`${page?.total.toLocaleString()??0} results`}</p><section>{(query?page?.instruments??[]:instruments.slice(0,25)).map(stockRow)}</section><div className="bnb-directory-pages"><button disabled={offset===0} onClick={()=>setOffset(n=>Math.max(0,n-BNB_PAGE_SIZE))}>Previous</button><button disabled={offset+(page?.instruments.length??0)>=(page?.total??0)} onClick={()=>setOffset(n=>n+BNB_PAGE_SIZE)}>Next results</button></div></dialog>
    <dialog ref={walletDialog} className="bnb-wallet-dialog"><button className="icon-button" aria-label="Close wallet" onClick={()=>walletDialog.current?.close()}><Icon name="close"/></button><h2>Your wallet</h2><p>{wallet}</p><span>{walletNetwork==='0x38'?'BNB Chain':'Select BNB Chain in your wallet to read holdings.'}</span><button className="secondary" onClick={()=>{generation.current++;accountRef.current=null;setWallet(null);setBalances({});setBalanceOwner('');walletDialog.current?.close();}}>Disconnect from XTXC</button></dialog>
  </div>;
}
